# Generated by Django 3.1.3 on 2020-11-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_historia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historia',
            old_name='recha',
            new_name='fecha',
        ),
    ]
