# Generated by Django 3.1.3 on 2020-12-03 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20201203_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='paciente',
        ),
        migrations.AddField(
            model_name='historia',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
            preserve_default=False,
        ),
    ]
