# Generated by Django 3.1.3 on 2020-12-02 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_auto_20201130_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
